// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:lang/docs/*": {
    params: {
      "lang": string;
      "*": string;
    };
  };
  "/:lang/api/search": {
    params: {
      "lang": string;
    };
  };
  "/:lang/llms.txt": {
    params: {
      "lang": string;
    };
  };
  "/:lang/llms-full.txt": {
    params: {
      "lang": string;
    };
  };
  "/:lang/llms.mdx/docs/*": {
    params: {
      "lang": string;
      "*": string;
    };
  };
  "/:lang": {
    params: {
      "lang": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:lang/docs/*" | "/:lang/api/search" | "/:lang/llms.txt" | "/:lang/llms-full.txt" | "/:lang/llms.mdx/docs/*" | "/:lang" | "/*";
  };
  "routes/root.tsx": {
    id: "routes/root";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/:lang/docs/*";
  };
  "routes/search.ts": {
    id: "routes/search";
    page: "/:lang/api/search";
  };
  "llms/index.ts": {
    id: "llms/index";
    page: "/:lang/llms.txt";
  };
  "llms/full.ts": {
    id: "llms/full";
    page: "/:lang/llms-full.txt";
  };
  "llms/mdx.ts": {
    id: "llms/mdx";
    page: "/:lang/llms.mdx/docs/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/:lang";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/root": typeof import("./app/routes/root.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/search": typeof import("./app/routes/search.ts");
  "llms/index": typeof import("./app/llms/index.ts");
  "llms/full": typeof import("./app/llms/full.ts");
  "llms/mdx": typeof import("./app/llms/mdx.ts");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};