import path from "node:path";
import fs from "fs-extra";
import { getFileNameFromUrl } from "./registry";
import type { Registry } from "../commands/add";

const HEADER = `/*
* THIS FILE IS AUTO-GENERATED BY LITEFY CLI
* DO NOT MODIFY MANUALLY, CHANGES WILL BE OVERWRITTEN
* Docs: https://litefy.top/
*/
`;

export async function syncStyleImports(
  cwd: string,
  stylesPath: string,
  installedStyles: string[],
  registry: Registry,
): Promise<void> {
  const files = installedStyles
    .map((name) => registry[name])
    .filter((entry) => entry?.type === "css")
    .map((entry) => getFileNameFromUrl(entry.url))
    .sort();

  const imports = ['@import "tailwindcss";', ...files.map((f) => `@import "./${f}";`)];
  const content = `${HEADER}${imports.join("\n")}\n`;

  const cssPath = path.resolve(cwd, stylesPath, "index.css");
  await fs.ensureDir(path.dirname(cssPath));
  const current = (await fs.pathExists(cssPath)) ? await fs.readFile(cssPath, "utf8") : null;
  if (current !== content) {
    await fs.writeFile(cssPath, content, "utf8");
  }
}
